# BoxKV Configuration File

# Storage Configuration
[storage]
# Directory where data will be stored
# Default: "./data"
data_dir = "./data"

# Size of the MemTable in megabytes (MB)
# Range: 1 to 1024 MB
# Default: 4
memtable_size_mb = 4

# Server Configuration
[server]
# The host address to bind the server to
# Default: "127.0.0.1"
host = "127.0.0.1"

# The port to listen on
# Default: 21524
port = 21524

